package lipid;

unit LipidScoreUnit;

// !! This rule does not include the lipid type, you shall add it.
// !! ** Same lipid type with the same number of double bonds and a higher number of carbons should have a higher RT
// This is one example of rules that only prints the factorial combination of all pairs eliminating the A-A combination.
rule "Score 1 for lipid pair with increasing RT and carbon count"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $carbonCount1 : lipid.getCarbonCount(),
        $doubleBondCount : lipid.getDoubleBondsCount(),
        $lipidType : lipid.getLipidType()
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getCarbonCount() > $carbonCount1,
        lipid.getDoubleBondsCount() == $doubleBondCount,
        lipid.getLipidType().equals($lipidType),
        rtMin > $rt1
    ]
then
    $a1.addScore(1.0d);  // Double
    $a2.addScore(1.0d);  // Double
    System.out.println("Scored 1 for annotations: " + $a1 + " and " + $a2);
end

rule "Score 1 for lipid pair with increasing RT and double bonds"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $carbonCount : lipid.getCarbonCount(),
        $doubleBondCount1 : lipid.getDoubleBondsCount(),
        $lipidType : lipid.getLipidType()
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getCarbonCount() == $carbonCount,
        lipid.getDoubleBondsCount() < $doubleBondCount1
        lipid.getLipidType().equals($lipidType),
        rtMin > $rt1,
    ]
then
    $a1.addScore(1.0d);  // Double
    $a2.addScore(1.0d);  // Double
    System.out.println("Scored 1 for annotations: " + $a1 + " and " + $a2);
end

rule "Score 1 for lipid pair with increasing RT and higher lipid type priority"
when
    $a1 : /annotations[
        $rt1 : rtMin,
        $lipid1 : lipid,
        $lipidType1 : lipid.getLipidType(),
        $carbonCount : lipid.getCarbonCount(),
        $doubleBonds : lipid.getDoubleBondsCount()
    ]
    $a2 : /annotations[
        this != $a1,
        $lipid2 : lipid,
        $lipidType2 : lipid.getLipidType(),
        $lipidType1 != $lipidType2,
        lipid.getCarbonCount() == $carbonCount,
        lipid.getDoubleBondsCount() == $doubleBonds,
        rtMin > $rt1,
        eval(LipidTypePriority.isMoreRetained($lipidType2, $lipidType1)) // $a2 more retained
    ]
then
    $a1.addScore(1.0d);
    $a2.addScore(1.0d);
    System.out.println("Scored +1 for lipid type order: " + $a1 + " and " + $a2);
end



rule "Negative evidence if RT follows opposite order to previous based on RT and carbon count"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $carbonCount1 : lipid.getCarbonCount(),
        $doubleBondCount : lipid.getDoubleBondsCount(),
        $lipidType : lipid.getLipidType()
    ]
    $a2 : /annotations [
        this != $a1,
        rtMin < $rt1
        lipid.getCarbonCount() > $carbonCount1,
        lipid.getDoubleBondsCount() == $doubleBondCount,
        lipid.getLipidType().equals($lipidType),
    ]
then
    $a1.addScore(-1.0d);
    $a2.addScore(-1.0d);  // Double
    System.out.println("Scored -1 for annotations: " + $a1 + " and " + $a2);
end

rule "Negative evidence if RT follows opposite order to previous based on RT and double bonds"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $carbonCount : lipid.getCarbonCount(),
        $doubleBondCount1 : lipid.getDoubleBondsCount(),
        $lipidType : lipid.getLipidType()
    ]
    $a2 : /annotations [
        this != $a1,
        lipid.getCarbonCount() == $carbonCount,
        lipid.getDoubleBondsCount() < $doubleBondCount1,
        lipid.getLipidType().equals($lipidType),
        rtMin < $rt1
    ]
then
    $a1.addScore(-1.0d);
    $a2.addScore(-1.0d);  // Double
    System.out.println("Scored -1 for annotations: " + $a1 + " and " + $a2);
end

rule "Negative evidence if RT follows opposite order to previous based on lipid type"
when
    $a1 : /annotations [
        $rt1 : rtMin,
        $carbonCount : lipid.getCarbonCount(),
        $doubleBondCount : lipid.getDoubleBondsCount(),
        $lipidType1 : lipid.getLipidType()
    ]
    $a2 : /annotations [
    this != $a1,
         lipid.getCarbonCount() == $carbonCount,
         lipid.getDoubleBondsCount() == $doubleBondCount,
         lipid.getLipidType() != $lipidType1,
         rtMin < $rt1
     ]
then
    $a1.addScore(-1.0d);  // Double
    $a2.addScore(-1.0d);  // Double
    System.out.println("Scored 1 for annotations: " + $a1 + " and " + $a2);
end

